name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      datastore:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    env:
      GO111MODULE: on
      DYNAMODB_LOCAL_ENDPOINT: http://127.0.0.1:8000

    steps:
      - name: Set up AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          go test -v ./... -tags="emulator"
