name: Statik
on:
  push:
    branches:
      - master
      - issue/66_citest

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Make statik
        run: |
          make statik

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - uses: actions/checkout@v2

      - name: Push
        run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          PATH="$PATH":"$HOME"/go/bin
          go get github.com/rakyll/statik
          pwd # debug
          ls -lah # debug
          make statik
          git add -f statik/
          git commit -m "update: statik"
          git push github HEAD:${GITHUB_REF}
